INSERT INTO Tipologie (nome) VALUES 
('Mouse'),
('Tastiera'),
('Monitor'),
('Stampante'),
('Altoparlanti'),
('Webcam'),
('Microfono'),
('Scheda madre'),
('Processore'),
('Memoria RAM'),
('Scheda video'),
('HDD'),
('SSD'),
('Alimentatore'),
('Dissipatore'),
('Case'),
('Cuffie');